# Banco PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=admin123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/estoque_db

# Gera/atualiza tabelas automaticamente
quarkus.hibernate-orm.database.generation=update

# Mostra o SQL no console (util para debug)
quarkus.hibernate-orm.log.sql=true
# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=origin,content-type,accept,authorization,x-requested-with
quarkus.http.cors.access-control-allow-credentials=true