# Banco PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=joao123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/estoque_db

# Gera/atualiza tabelas automaticamente
quarkus.hibernate-orm.database.generation=update

# Mostra o SQL no console (�til para debug)
quarkus.hibernate-orm.log.sql=true